version: "3.8"

services: 
  www:
    build: docker/php
    container_name: ecoride_symfony_php
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
    networks:
      - ecoride_symfony

  mysql:
    image: mysql
    container_name: ecoride_symfony_mysql
    volumes:
      - ./var/db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - ecoride_symfony

  phpmyadmin:
    image: phpmyadmin
    container_name: ecoride_symfony_phpmyadmin
    ports:
      - 8780:80
    networks:
      - ecoride_symfony  

networks:
  ecoride_symfony: